project:
  type: website

website:
  title: "Manitoba Arts Council Survey Results"
  navbar:
    search: false
    right: []

format:
  html:
    theme:
     - default
     - styles.scss
    include-before-body: logo.html
    toc: true
  pptx: default



