---
title: "Strategic Planning Survey Results"
format:
  dashboard:
    theme: styles.scss
logo: assets/MAC_Logo-RGB_Colour-Stack.jpg
---


```{r}
#| label: setup
#| include: false

library(tidyverse)
library(flextable)
library(janitor)
library(scales)
library(sf)
library(rnaturalearth)
library(ggtext)


# set ggplot themes
plot_theme <- function() {
  theme_minimal(base_size = 16)
}

# set colours
blue <- "#7fc5c5"
green <- "#b7b23a"
mustard <- "#ac8732"
yellow <- "#f2b643"
orange <- "#e9913d"
red <- "#dd4f34"
magenta <- "#cd2e6b"
brick <- "#9f4125"

```

```{r}
#| label: load-data
#| include: false

#source("scripts/import-data.R")

data <- read_rds("data/survey_data_clean.rds")

data <- data |>
  mutate(across(
    where(is.factor),
    ~ fct_na_value_to_level(.x, level = "Missing")
  )) |>
  mutate(
    funded_status = case_when(
      funded_past_3_yrs == "Yes" & applied_not_funded == "Yes" ~ "Funded",
      funded_past_3_yrs == "Yes" & applied_not_funded == "No" ~ "Funded",
      funded_past_3_yrs == "No" &
        applied_not_funded == "Yes" ~ "Applied, not funded",
      funded_past_3_yrs == "No" &
        applied_not_funded == "No" ~ "Did not apply, not funded",
      TRUE ~ "Missing"
    )
  ) |>
  mutate(
    funded_status = factor(
      funded_status,
      levels = c(
        "Funded",
        "Applied, not funded",
        "Did not apply, not funded",
        "Missing"
      )
    )
  ) |>
  mutate(
    role_grouped = case_when(
      org_role %in%
        c(
          "Individual Artist",
          "Indigenous Knowledge Keeper",
          "Student of the Arts",
          "Teacher"
        ) ~ "Individual",
      org_role %in%
        c(
          "Arts/Cultural Organization",
          "Educational Institution (e.g., school, post-secondary)",
          "Community-based Organization",
          "Collective / Group of Artists"
        ) ~ "Organization",
      TRUE ~ NA
    )
  ) |>
  mutate(
    postal_code = str_replace_all(postal_code, " ", ""),
    postal_code = str_to_upper(postal_code),
    fsa = str_sub(postal_code, start = 1, end = 3)
  ) |>
  mutate(
    fsa = case_when(
      str_starts(fsa, "R") ~ fsa,
      TRUE ~ NA
    )
  )


# load regions and link to data
regions <- read_csv("data/mb-region-fsa-table.csv") |>
  select(-dup)


# link region to data
data <- data |>
  mutate(.row_id = row_number()) |>
  left_join(regions, by = "fsa", relationship = "many-to-many") |>
  group_by(.row_id) |>
  slice_sample(n = 1) |>
  ungroup() |>
  mutate(
    location = case_when(
      region == "Capital Region" ~ "Winnipeg Area",
      TRUE ~ "Outside Wpg"
    )
  )

data_applied <- data |> 
  filter(funded_status != "Did not apply, not funded")

# Create functions
source("scripts/functions.R")

write_csv(data, "data/survey_data_clean.csv")

```



# Overview

## Row {height=20%}

```{r}
#| label: updated
#| content: valuebox
#| title: "Updated:"

list(
  color = blue,
  value = format(Sys.Date(), "%b %d, %Y")
)

```


```{r}
#| content: valuebox
#| title: "Respondents:"
#| label: num_respondents

num_responses_all <- data |>
  count() |>
  pull()

num_funded <- data |>
  filter(funded_past_3_yrs == "Yes") |>
  count() |>
  pull()

pct_funded <- num_funded / num_responses_all

list(
  color = blue,
  value = num_responses_all
)


```

```{r}
#| content: valuebox
#| title: "Funded in the last 3 years:"
#| label: funded

list(
  color = blue,
  value = paste0(round(pct_funded * 100, 0), "%")
)


```

## Row {height=80%}

### Column {width=40%}

#### Row {height=60%}


```{r map}
#| title: Regional Distribution
#| label: map

# get manitoba boundary shape
mb_boundary_map <- ne_states(country = "canada", returnclass = "sf") |>
  filter(name == "Manitoba") |>
  st_transform(crs = 4326) |>
  st_make_valid() |>
  st_union()

# get mb economic regions shapefiles
mb_econ_regions_sf <- read_sf("mb_economic-regions-shape-files") |>
  clean_names() |>
  st_transform(crs = 4326)

mb_econ_regions_sf <- mb_econ_regions_sf |>
  mutate(
    economic_r = case_when(
      economic_r == "Winnipeg" ~ "Capital Region",
      economic_r == "Southwest" ~ "Westman",
      economic_r == "Southeast" ~ "Eastman",
      economic_r == "South Central" ~ "Pembina Valley",
      economic_r == "Parkland" ~ "Parklands",
      economic_r == "North Central" ~ "Central Plains",
      economic_r == "North" ~ "Norman",
      economic_r == "Interlake" ~ "Interlake"
    )
  )

# grab fsa and link to shape file
mac_fsa_data <- data |>
  select(fsa, region)


mac_fsa_data_grouped <- mac_fsa_data |>
  group_by(region) |>
  count()

# link counts to shapefile

mb_econ_regions_sf <- mb_econ_regions_sf |>
  left_join(mac_fsa_data_grouped, by = c("economic_r" = "region"))

# create categories for n

mb_econ_regions_sf <- mb_econ_regions_sf |>
  mutate(
    n_categories = case_when(
      is.na(n) ~ "No data",
      n <= 50 ~ "1 - 50",
      n <= 100 ~ "51 - 100",
      n <= 150 ~ "101 - 150",
      n > 150 ~ "Over 150"
    ),
    n_categories = factor(
      n_categories,
      levels = c("1 - 50", "51 - 100", "101 - 150", "Over 150", "No data")
    )
  )


ggplot() +
  geom_sf(
    data = mb_boundary_map,
    fill = "grey98",
    colour = "grey80",
    linewidth = 0.4
  ) +
  geom_sf(
    data = mb_econ_regions_sf,
    (aes(fill = n_categories)),
    colour = "white"
  ) +
  scale_fill_manual(
    values = c(
      "1 - 50" = yellow,
      "51 - 100" = orange,
      "101 = 150" = red,
      "Over 150" = brick,
      "No data" = "grey90"
    )
  ) +
  labs(fill = NULL) +
  theme_void()


```

#### Row {height=40%}
```{r}
#| label: regions_bar

t <- mb_econ_regions_sf |> 
  st_drop_geometry() |> 
  select(economic_r, n) |> 
  mutate(economic_r = fct_reorder(economic_r, n))

ggplot(data = t,
mapping = aes(x = economic_r,
y = n)) +
  geom_col(fill = green) +
  geom_text(aes(label = n),
  hjust = -.5) +
  coord_flip() +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +
  labs(y = "",
  x = "") +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size = 11),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank())

```

### Column {width=60%}


```{r org_role}
#| title: Survey Respondents by Role
#| label: respondents_by_role

data |>
  mutate(
    org_role = str_remove(org_role, " \\(.*\\)"),
    org_role = fct_infreq(org_role),
    org_role = fct_relevel(org_role, "Missing", after = Inf),
    org_role = fct_rev(org_role)
  ) |>
  ggplot(aes(x = org_role, y = after_stat(prop))) +
  geom_bar(aes(group = 1), fill = green) +
  geom_text(
    aes(label = after_stat(count), y = after_stat(prop), group = 1),
    stat = "count",
    hjust = -0.25,
    size = 3.5
  ) +
  coord_flip() +
  scale_y_continuous(labels = percent_format(),
  expand = c(0, 0.1)) +
  labs(
    y = "",
    x = "",
    caption = "Bar lengths are proportional. The data label indicates frequency."
  ) +
  plot_theme() +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_line(linewidth = 0.5),
    plot.caption.position = "plot",
    plot.caption = element_text(size = 10, hjust = 0)
  )


```




```{r}
#| title: Primary Areas of Artistic and Organizational Focus
#| label: area_of_art_focus

data |>
  select(primary_focus) |>
  mutate(
    primary_focus = fct_infreq(primary_focus),
    primary_focus = fct_relevel(primary_focus, "Missing", after = Inf)
  ) |>
  ggplot(aes(
    x = primary_focus,
    y = after_stat(prop),
  )) +
  geom_bar(aes(group = 1), fill = green) +
  geom_text(
    aes(
      label = paste0("n = ", after_stat(count)),
      y = after_stat(prop),
      group = 1
    ),
    stat = "count",
    vjust = -.5,
    size = 3.5
  ) +
  scale_y_continuous(labels = percent_format()) +
  scale_x_discrete(labels = function(x) str_wrap(x, 8)) +
  labs(y = "", x = "") +
  plot_theme() +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank()
  )
```


# All Results

## Row

### Column {.tabset}

```{r}
#| title: "Confidence"
#| label: confidence_all

data |>
  filter(
    !confident_in_mac_ability %in% c("Don’t know enough to answer", "Missing")
  ) |>
  ggplot(aes(x = confident_in_mac_ability, y = after_stat(prop))) +
  geom_bar(aes(group = 1), fill = green) +
  geom_text(
    aes(
      label = paste0("n = ", after_stat(count)),
      y = after_stat(prop),
      group = 1
    ),
    stat = "count",
    vjust = -.5,
    size = 4
  ) +
  scale_y_continuous(labels = percent_format(), limits = c(0, .75)) +
  labs(
    title = "Confidence in MAC's Ability to Fullfill Its Purpose",
    x = "",
    y = ""
  ) +
  plot_theme() +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank()
  )
```



```{r}
#| title: "By Role"
#| label: confidence_by_role

plot_confidence_by_group(data, role_grouped)


```


```{r}
#| title: "Funding"
#| label: confidence_by_funding

plot_confidence_by_group(data, funded_status)
```


```{r}
#| title: "Location"
#| label: confidence_by_location

plot_confidence_by_group(data, location)

```



### Column {.tabset}

```{r}
#| title: "Satisfaction"
#| label: satisfaction_all

ratings_data <- data |>
  select(role_grouped, deadline_comms:complaints_process) |>
  pivot_longer(
    cols = -role_grouped,
    names_to = "question",
    values_to = "response"
  ) |>
  filter(response != "Don't know", response != "Missing") |>
  group_by(question, response) |>
  count() |>
  group_by(question) |>
  mutate(pct = n / sum(n)) |>
  ungroup() |>
  mutate(
    question = case_when(
      question == "trasparent_granting" ~ "Transparency of decision making",
      question == "response_results" ~ "Response time for grant results",
      question == "response_enquiries" ~ "Responsiveness to enquiries",
      question == "manipogo" ~ "Usability of Manipogo",
      question == "guidelines_comms" ~ "Clarity about grant deadlines",
      question == "feedback" ~ "Helpfulness of MAC feedback in grant process",
      question == "deadline_comms" ~ "Clarity about deadlines and MAC activity",
      question == "complaints_process" ~ "MAC's feedback/complaints process"
    )
  ) |>
  mutate(
    response = factor(
      response,
      levels = c("Poor", "Fair", "Good", "Excellent")
    ),
    pct = if_else(response %in% c("Poor", "Fair"), -pct, pct),
    pct_label = if_else(
      abs(pct) < 0.05,
      NA,
      paste0(abs(round(pct * 100, 0)), "%")
    ),
    side = if_else(response %in% c("Poor", "Fair"), "neg", "pos")
  )


neg_levels <- c("Poor", "Fair")
pos_levels <- c("Good", "Excellent")

labels_pos <- ratings_data |>
  filter(side == "pos") |>
  arrange(question, factor(response, levels = c("Good", "Excellent"))) |>
  group_by(question) |>
  mutate(y_mid = cumsum(pct) - pct / 2) |>
  ungroup()

labels_neg <- ratings_data |>
  filter(side == "neg") |>
  mutate(width = abs(pct)) |>
  arrange(question, factor(response, levels = c("Fair", "Poor"))) |>
  group_by(question) |>
  mutate(y_mid = -(cumsum(width) - width / 2)) |>
  ungroup()

labels_df <- bind_rows(
  select(labels_pos, question, response, pct_label, y_mid),
  select(labels_neg, question, response, pct_label, y_mid)
)

ratings_data |>
  ggplot() +
  # left side
  geom_col(
    data = filter(ratings_data, side == "neg"),
    aes(x = question, y = pct, fill = response),
    position = "stack",
    colour = "white"
  ) +
  geom_col(
    data = filter(ratings_data, side == "pos"),
    aes(x = question, y = pct, fill = response),
    position = position_stack(reverse = TRUE),
    colour = "white"
  ) +
  geom_text(
    data = labels_df,
    aes(x = question, y = y_mid, label = pct_label),
    size = 3.25,
    colour = "floralwhite",
    fontface = "bold"
  ) +
  coord_flip() +
  geom_hline(yintercept = 0, colour = "floralwhite", linewidth = .25) +
  scale_y_continuous(labels = percent_format()) +
  scale_x_discrete(labels = function(x) str_wrap(x, 25)) +
  scale_fill_manual(
    values = c(
      "Poor" = red,
      "Fair" = orange,
      "Good" = green,
      "Excellent" = blue
    )
  ) +
  labs(
    title = "Satisfaction with MAC's Services and Processes",
    x = "",
    y = "",
    fill = ""
  ) +
  plot_theme() +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_text(hjust = 0, size = 10),
    legend.position = "bottom"
  )
```

```{r}
#| title: "By Role"
#| label: satisfaction_by_role

plot_positive_satisfaction_by_group(data, role_grouped)
```


```{r}
#| title: "Funding"
#| label: satisfaction_by_funding

plot_positive_satisfaction_by_group(data, funded_status)

```


```{r}
#| title: "Location"
#| label: satisfaction_by_location

plot_positive_satisfaction_by_group(data, location)

```

## Row

### Column {.tabset}

```{r}
#| title: "Connection"
#| label: connection_all

data |>
  select(connection_to_arts_community) |>
  filter(connection_to_arts_community != "Missing") |>
  ggplot() +
  geom_bar(
    aes(x = connection_to_arts_community, y = after_stat(prop), group = 1),
    fill = green
  ) +
  geom_text(
    aes(x = connection_to_arts_community,
      label = paste0("n = ", after_stat(count)),
      y = after_stat(prop),
      group = 1
    ),
    stat = "count",
    vjust = -.5,
    size = 4
  ) +
  scale_y_continuous(labels = percent_format()) +
  labs(x = "", y = "", title = "Connection to Arts & Cultural Community") +
  plot_theme() +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank()
  )
```

```{r}
#| title: "By Role"
#| label: connection_by_role

plot_connection_by_group(data, role_grouped)
```

```{r}
#| title: "Funding"
#| label: connection_by_funding

plot_connection_by_group(data, funded_status)

```

```{r}
#| title: "Location"
#| label: connection_by_location

plot_connection_by_group(data, location)


```

### Column {.tabset}



```{r}
#| title: "Ranked Needs"
#| label: ranking_all

plot_title <- "Ranked options are listed across the bottom of the grid. Each column shows ranks from high (1) to low (9). The colour of the square represents the proportion of people assigning the corresponding rank to each item. The darker the colour, the higher the number of people assigning that rank."

ranking_data <- data |>
  select(id, starts_with("rank")) |>
  pivot_longer(
    cols = -id,
    names_to = "item",
    values_to = "rank"
  ) |>
  filter(rank != "Missing") |>
  mutate(
    item = str_remove(item, "rank_"),
    rank = as.numeric(rank),
    n_total = n_distinct(id)
  ) |>
  mutate(item = str_replace(item, "_", " "), item = str_to_title(item)) |>
  group_by(item, rank) |>
  summarise(pct = n() / first(n_total) * 100, .groups = "drop")

ranking_data |>
  ggplot(aes(y = factor(rank), x = item, fill = pct)) +
  geom_tile(color = "white") +
  scale_y_discrete(limits = as.character(9:1)) +
  scale_x_discrete() +
  scale_fill_gradient(low = "white", high = mustard) +
  labs(title = plot_title, y = "Rank (1 = High, 9 = Low)", x = "", fill = "%") +
  plot_theme() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_textbox_simple(size = 12,
    margin = margin(b = 5)),
    plot.title.position = "plot",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```

```{r}
#| title: "Individuals"
#| label: ranking_individuals

plot_title <- "Ranked options are listed across the bottom of the grid. Each column shows ranks from high (1) to low (9). The colour of the square represents the proportion of people assigning the corresponding rank to each item. The darker the colour, the higher the number of people assigning that rank."

ranking_data <- data |>
  filter(role_grouped == "Individual") |> 
  select(id, starts_with("rank")) |>
  pivot_longer(
    cols = -id,
    names_to = "item",
    values_to = "rank"
  ) |>
  filter(rank != "Missing") |>
  mutate(
    item = str_remove(item, "rank_"),
    rank = as.numeric(rank),
    n_total = n_distinct(id)
  ) |>
  mutate(item = str_replace(item, "_", " "), item = str_to_title(item)) |>
  group_by(item, rank) |>
  summarise(pct = n() / first(n_total) * 100, .groups = "drop")

ranking_data |>
  ggplot(aes(y = factor(rank), x = item, fill = pct)) +
  geom_tile(color = "white") +
  scale_y_discrete(limits = as.character(9:1)) +
  scale_x_discrete() +
  scale_fill_gradient(low = "white", high = mustard) +
  labs(title = plot_title, y = "Rank (1 = High, 9 = Low)", x = "", fill = "%") +
  plot_theme() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_textbox_simple(size = 12, margin = margin(b = 5)),
    plot.title.position = "plot",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```

```{r}
#| title: "Organizations"
#| label: ranking_organization

plot_title <- "Ranked options are listed across the bottom of the grid. Each column shows ranks from high (1) to low (9). The colour of the square represents the proportion of people assigning the corresponding rank to each item. The darker the colour, the higher the number of people assigning that rank."

ranking_data <- data |>
  filter(role_grouped == "Organization") |> 
  select(id, starts_with("rank")) |>
  pivot_longer(
    cols = -id,
    names_to = "item",
    values_to = "rank"
  ) |>
  filter(rank != "Missing") |>
  mutate(
    item = str_remove(item, "rank_"),
    rank = as.numeric(rank),
    n_total = n_distinct(id)
  ) |>
  mutate(item = str_replace(item, "_", " "), item = str_to_title(item)) |>
  group_by(item, rank) |>
  summarise(pct = n() / first(n_total) * 100, .groups = "drop")

ranking_data |>
  ggplot(aes(y = factor(rank), x = item, fill = pct)) +
  geom_tile(color = "white") +
  scale_y_discrete(limits = as.character(9:1)) +
  scale_x_discrete() +
  scale_fill_gradient(low = "white", high = mustard) +
  labs(title = plot_title, y = "Rank (1 = High, 9 = Low)", x = "", fill = "%") +
  plot_theme() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_textbox_simple(size = 12,
    margin = margin(b = 5)),
    plot.title.position = "plot",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```


# Applicants Only

## Row

### Column {.tabset}

```{r}
#| label: confidence_applicants
#| title: "Confidence"

data |>
  filter(
    !confident_in_mac_ability %in% c("Don’t know enough to answer", "Missing"),
    funded_status != "Did not apply, not funded"
  ) |>
  ggplot(aes(x = confident_in_mac_ability, y = after_stat(prop))) +
  geom_bar(aes(group = 1), fill = green) +
  geom_text(
    aes(
      label = paste0("n = ", after_stat(count)),
      y = after_stat(prop),
      group = 1
    ),
    stat = "count",
    vjust = -.5,
    size = 4
  ) +
  scale_y_continuous(labels = percent_format(), limits = c(0, .75)) +
  labs(
    title = "Confidence in MAC's Ability to Fullfill Its Purpose",
    subtitle = "Includes only those that have applied in the last 3 years",
    x = "",
    y = ""
  ) +
  plot_theme() +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank()
  )
```


```{r}
#| title: "By Role"
#| label: confidence_by_role_applied

plot_confidence_by_group(data_applied, role_grouped, subtitle = "Includes only those that have applied in the last 3 years")



```


```{r}
#| title: "Funding"
#| label: confidence_by_funding_applied



plot_confidence_by_group(data_applied, funded_status, subtitle = "Includes only those that have applied in the last 3 years")
```


```{r}
#| title: "Location"
#| label: confidence_by_location_applied

plot_confidence_by_group(data_applied, location, subtitle = "Includes only those that have applied in the last 3 years")
```

### Column {.tabset}

```{r}
#| title: "Satisfaction"
#| label: satisfaction_applicants

ratings_data <- data |>
  filter(funded_status != "Did not apply, not funded") |> 
  select(role_grouped, deadline_comms:complaints_process) |>
  pivot_longer(
    cols = -role_grouped,
    names_to = "question",
    values_to = "response"
  ) |>
  filter(response != "Don't know", response != "Missing") |>
  group_by(question, response) |>
  count() |>
  group_by(question) |>
  mutate(pct = n / sum(n)) |>
  ungroup() |>
  mutate(
    question = case_when(
      question == "trasparent_granting" ~ "Transparency of decision making",
      question == "response_results" ~ "Response time for grant results",
      question == "response_enquiries" ~ "Responsiveness to enquiries",
      question == "manipogo" ~ "Usability of Manipogo",
      question == "guidelines_comms" ~ "Clarity about grant deadlines",
      question == "feedback" ~ "Helpfulness of MAC feedback in grant process",
      question == "deadline_comms" ~ "Clarity about deadlines and MAC activity",
      question == "complaints_process" ~ "MAC's feedback/complaints process"
    )
  ) |>
  mutate(
    response = factor(
      response,
      levels = c("Poor", "Fair", "Good", "Excellent")
    ),
    pct = if_else(response %in% c("Poor", "Fair"), -pct, pct),
    pct_label = if_else(
      abs(pct) < 0.05,
      NA,
      paste0(abs(round(pct * 100, 0)), "%")
    ),
    side = if_else(response %in% c("Poor", "Fair"), "neg", "pos")
  )


neg_levels <- c("Poor", "Fair")
pos_levels <- c("Good", "Excellent")

labels_pos <- ratings_data |>
  filter(side == "pos") |>
  arrange(question, factor(response, levels = c("Good", "Excellent"))) |>
  group_by(question) |>
  mutate(y_mid = cumsum(pct) - pct / 2) |>
  ungroup()

labels_neg <- ratings_data |>
  filter(side == "neg") |>
  mutate(width = abs(pct)) |>
  arrange(question, factor(response, levels = c("Fair", "Poor"))) |>
  group_by(question) |>
  mutate(y_mid = -(cumsum(width) - width / 2)) |>
  ungroup()

labels_df <- bind_rows(
  select(labels_pos, question, response, pct_label, y_mid),
  select(labels_neg, question, response, pct_label, y_mid)
)

ratings_data |>
  ggplot() +
  # left side
  geom_col(
    data = filter(ratings_data, side == "neg"),
    aes(x = question, y = pct, fill = response),
    position = "stack",
    colour = "white"
  ) +
  geom_col(
    data = filter(ratings_data, side == "pos"),
    aes(x = question, y = pct, fill = response),
    position = position_stack(reverse = TRUE),
    colour = "white"
  ) +
  geom_text(
    data = labels_df,
    aes(x = question, y = y_mid, label = pct_label),
    size = 3.25,
    colour = "floralwhite",
    fontface = "bold"
  ) +
  coord_flip() +
  geom_hline(yintercept = 0, colour = "floralwhite", linewidth = .25) +
  scale_y_continuous(labels = percent_format()) +
  scale_x_discrete(labels = function(x) str_wrap(x, 25)) +
  scale_fill_manual(
    values = c(
      "Poor" = red,
      "Fair" = orange,
      "Good" = green,
      "Excellent" = blue
    )
  ) +
  labs(
    title = "Satisfaction with MAC's Services and Processes",
    subtitle = "Includes only those that have applied in the last 3 years",
    x = "",
    y = "",
    fill = ""
  ) +
  plot_theme() +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_text(hjust = 0, size = 10),
    legend.position = "bottom"
  )
```

```{r}
#| title: "By Role"
#| label: satisfaction_by_role_applied

plot_positive_satisfaction_by_group(data_applied, role_grouped, caption = "Includes only those that have applied in the last 3 years")
```


```{r}
#| title: "Funding"
#| label: "Satisfaction_by_funding_applied"

plot_positive_satisfaction_by_group(data_applied, funded_status,
caption = "Includes only those that have applied in the past 3 years")

```


```{r}
#| title: "Location"
#| label: satisfaction_by_location_applied

plot_positive_satisfaction_by_group(data_applied, location,
caption = "Includes only those that have applied in the past 3 years")

```

## Row

### Column {.tabset}

```{r}
#| title: "Connection"
#| label: connection_applied

data |>
  filter(funded_status != "Did not apply, not funded") |> 
  select(connection_to_arts_community) |>
  filter(connection_to_arts_community != "Missing") |>
  ggplot() +
  geom_bar(
    aes(x = connection_to_arts_community, y = after_stat(prop), group = 1),
    fill = green
  ) +
  geom_text(
    aes(x = connection_to_arts_community,
      label = paste0("n = ", after_stat(count)),
      y = after_stat(prop),
      group = 1
    ),
    stat = "count",
    vjust = -.5,
    size = 4
  ) +
  scale_y_continuous(labels = percent_format()) +
  labs(x = "", y = "", title = "Connection to Arts & Cultural Community", subtitle = "Includes only those that have applied in the last 3 years") +
  plot_theme() +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank()
  )
```

```{r}
#| title: "By Role"
#| label: connection_by_role_applied

plot_connection_by_group(data_applied, role_grouped,
subtitle = "Includes only those that have appled in the last 3 years")
```

```{r}
#| title: "Funding"
#| label: connection_by_funding_applied

plot_connection_by_group(data_applied, funded_status,
subtitle = "Includes only those that have applied in the last 3 years")

```

```{r}
#| title: "Location"
#| label: connection_by_location_applied

plot_connection_by_group(data_applied, location,
subtitle = "Includes only those that have applied in the last 3 years")


```

### Column {.tabset}



```{r}
#| title: "Ranked Needs"
#| label: ranking_all_applied

plot_title <- "Ranked options are listed across the bottom of the grid. Each column shows ranks from high (1) to low (9). The colour of the square represents the proportion of people assigning the corresponding rank to each item. The darker the colour, the higher the number of people assigning that rank."

ranking_data <- data |>
  filter(funded_status != "Did not apply, not funded") |> 
  select(id, starts_with("rank")) |>
  pivot_longer(
    cols = -id,
    names_to = "item",
    values_to = "rank"
  ) |>
  filter(rank != "Missing") |>
  mutate(
    item = str_remove(item, "rank_"),
    rank = as.numeric(rank),
    n_total = n_distinct(id)
  ) |>
  mutate(item = str_replace(item, "_", " "), item = str_to_title(item)) |>
  group_by(item, rank) |>
  summarise(pct = n() / first(n_total) * 100, .groups = "drop")

ranking_data |>
  ggplot(aes(y = factor(rank), x = item, fill = pct)) +
  geom_tile(color = "white") +
  scale_y_discrete(limits = as.character(9:1)) +
  scale_x_discrete() +
  scale_fill_gradient(low = "white", high = mustard) +
  labs(title = plot_title, 
  caption = "Includes only those that have applied in the last 3 years",
  y = "Rank (1 = High, 9 = Low)", x = "", fill = "%") +
  plot_theme() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_textbox_simple(size = 12,
    margin = margin(b = 5)),
    plot.title.position = "plot",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```

```{r}
#| title: "Individuals"
#| label: ranking_individuals_applied

plot_title <- "Ranked options are listed across the bottom of the grid. Each column shows ranks from high (1) to low (9). The colour of the square represents the proportion of people assigning the corresponding rank to each item. The darker the colour, the higher the number of people assigning that rank."

ranking_data <- data |>
  filter(role_grouped == "Individual",
  funded_status != "Did not apply, not funded") |> 
  select(id, starts_with("rank")) |>
  pivot_longer(
    cols = -id,
    names_to = "item",
    values_to = "rank"
  ) |>
  filter(rank != "Missing") |>
  mutate(
    item = str_remove(item, "rank_"),
    rank = as.numeric(rank),
    n_total = n_distinct(id)
  ) |>
  mutate(item = str_replace(item, "_", " "), item = str_to_title(item)) |>
  group_by(item, rank) |>
  summarise(pct = n() / first(n_total) * 100, .groups = "drop")

ranking_data |>
  ggplot(aes(y = factor(rank), x = item, fill = pct)) +
  geom_tile(color = "white") +
  scale_y_discrete(limits = as.character(9:1)) +
  scale_x_discrete() +
  scale_fill_gradient(low = "white", high = mustard) +
  labs(title = plot_title, 
  caption = "Includes only individual artists that have applied in the last 3 years",
  y = "Rank (1 = High, 9 = Low)", x = "", fill = "%") +
  plot_theme() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_textbox_simple(size = 12,
    margin = margin(b = 5)),
    plot.title.position = "plot",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```

```{r}
#| title: "Organizations"
#| label: ranking_organization_applied

plot_title <- "Ranked options are listed across the bottom of the grid. Each column shows ranks from high (1) to low (9). The colour of the square represents the proportion of people assigning the corresponding rank to each item. The darker the colour, the higher the number of people assigning that rank."

ranking_data <- data |>
  filter(funded_status != "Did not apply, not funded",
  role_grouped == "Organization") |> 
  select(id, starts_with("rank")) |>
  pivot_longer(
    cols = -id,
    names_to = "item",
    values_to = "rank"
  ) |>
  filter(rank != "Missing") |>
  mutate(
    item = str_remove(item, "rank_"),
    rank = as.numeric(rank),
    n_total = n_distinct(id)
  ) |>
  mutate(item = str_replace(item, "_", " "), item = str_to_title(item)) |>
  group_by(item, rank) |>
  summarise(pct = n() / first(n_total) * 100, .groups = "drop")

ranking_data |>
  ggplot(aes(y = factor(rank), x = item, fill = pct)) +
  geom_tile(color = "white") +
  scale_y_discrete(limits = as.character(9:1)) +
  scale_x_discrete() +
  scale_fill_gradient(low = "white", high = mustard) +
  labs(title = plot_title, 
  caption = "Includes only organizations that have applied for funding in the last 3 years",
  y = "Rank (1 = High, 9 = Low)", x = "", fill = "%") +
  plot_theme() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_textbox_simple(size = 12,
    margin = margin(b = 5)),
    plot.title.position = "plot",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```
